export let users = [
  { 
    id: 1,
    surname: 'Аркипян',
    name: 'Вася',
    thirdName: 'Аркипянович',
    phone: '+79284676823',
    email: 'kto-to@mail.ru',
    birthDate: 1991,
  },
  { 
    id: 2,
    surname: 'Батаева',
    name: 'Мария',
    thirdName: 'Васильевна',
    phone: '+79284676823',
    email: 'kto-to@mail.ru',
    birthDate: 1992,
  },
    
  { id: 3,
    surname: 'Де-Фомин',
    name: 'Алехей',
    thirdName: 'Де-фоминович',
    phone: '+79284676823',
    email: 'kto-to@mail.ru',
    birthDate: 1995,
  },
  { 
    id: 4,
    surname: 'Галкин',
    name: 'Илья',
    thirdName: 'Загуляевич',
    phone: '+79284676823',
    email: 'kto-to@mail.ru',
    birthDate: 1899,
  },
  { 
    id: 5,
    surname: 'Фамилий',
    name: 'Роман',
    thirdName: 'Отчествиевич',
    phone: '+79284676823',
    email: 'kto-to@mail.ru',
    birthDate: 1901,
  },
]
